app = "bc-redis"
primary_region = "lax"

[mounts]
  destination = "/data"
  source = "bc_redis_data"

[metrics]
  port = 9091
  path = "/metrics"

# Use the Docker image instead of building from source

[build]
  dockerfile = "Dockerfile"
  [build.args]
    ENV = "production"
    REDIS_VERSION = "7.2"

[env]
  ENV = "production"
  APPENDONLY="yes"
  MAXMEMORY_POLICY="noeviction"
  FLY_VM_MEMORY_MB="256"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
